name: tempguard_flutter_app
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter
  syncfusion_flutter_charts: ^21.2.9
  fl_chart: ^0.50.5
  onboarding: ^3.1.0
  flutter_speed_dial: ^7.0.0
  flutter_expandable_fab: ^1.8.1
  flutter_svg: ^2.0.7
  page_transition: ^2.0.1-nullsafety.0
  path_provider: ^2.0.15
  share_plus: ^7.0.2
  flutter_file_dialog: ^3.0.1
  table_calendar: ^3.0.9






  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  weather_icons: ^3.0.0
  flutter_animated_button: ^2.0.3
  sn_progress_dialog: ^1.1.3
  mvc_pattern: ^8.12.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
  rxdart: ^0.27.1
  url_launcher: ^6.0.9
  http: ^1.1.0
  jwt_decoder: ^2.0.1
  flutter_local_notifications: ^15.1.1
  shared_preferences: ^2.2.0
  dart_amqp: ^0.2.5
  flutter_background_service: ^5.0.1
flutter_icons:
  android: "launcher_icon"
  image_path: "android/asset/icons/asqii-icon.png"




  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^2.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - asset/asqii.png
    - asset/logo.png
    - asset/profil.png
    - asset/Images/onbroading1.png
    - asset/Images/onbroading2.png
    - asset/Images/onbroading3.png
    - asset/Images/logo_login.png
    - asset/Images/Google.png
    - asset/Images/forget_password.png
    - asset/Images/rest_pass.png
    - asset/Images/asqii.black.png
    - asset/Images/facebook.png
    - asset/Images/globe.png
    - asset/Images/mail.png
    - asset/Images/linkedin.png
    - asset/Images/chevron-right.png
    - asset/Images/pen.png
    - asset/Images/bin.png
    - asset/Images/add.png
    - asset/Images/home.png
    - asset/Images/settings.png
    - asset/Images/custom_alert.svg
    - asset/Images/add_alert_nav.svg
    - asset/Images/final_Alert.svg
    - asset/Images/Alerts_Icon.svg


  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Montserrat
      fonts:
        - asset: fonts/Montserrat-Regular.ttf
        - asset: fonts/Montserrat-Bold.ttf
          weight: 700
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
